config/routes.rb
Walk30Experiment::Application.routes.draw do
  
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  devise_scope :user do
    match "/login", to: "devise/sessions#new"
  end
    
  resources :participants do
    collection do
      get :active
      put :setNextReminders
      get :mass_message
    end
    member do
      post :deliverMessage
    end
  end

  get "/twilio/receive/" => "static_pages#twilio_receive", :defaults => { :format => 'xml' } 

  resources :messages do
    collection do
      put :cancel_pending
      put :autoflag
    end
    member do
      put :deliver
      put :cancel
      put :flagPositive
      put :flagNegative
      put :flagNeutral
    end
  end

  root to: 'static_pages#home'
  match '/contact', to: 'static_pages#contact'
  match '/signup', to: "participants#new"
  match '/instructions', to: 'static_pages#instructions'
  match '/welcome', to: 'static_pages#welcome'
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
  def contact
  end
  
  def instructions
  end
  
  def welcome
  end
    
  def twilio_receive
    phone = params[:From][2..11]
    content = params[:Body]
    account_sid = params[:AccountSid]
    participant = Participant.withPhone(phone)
    @sms = nil #This is the body of the automated reply message. If nil, no reply message will be sent.
    if participant and account_sid == Message::TWILIO_ACCOUNT_SID
      if participant.messages
        lastMessage = participant.messages.last
        if lastMessage.received? and lastMessage.content==content and (DateTime.now - lastMessage.created_at) < 30
          logger.info "Duplicate message received but not recorded."
          return
        else
          participant.receiveMessage(content,Message::TEXT)
          #@sms = participant.email
        end
      end
    end
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/contact.html.haml
-provide(:title, 'Contact')
.container-narrow
	%h2 Email us at:
	%p walk30project at gmail

app/views/static_pages/home.html.haml
-provide(:title, 'Walk 30 minutes a day for a happier, healthier you!')
.container-narrow
	.jumbotron.hero-unit
		%h1 The Walk30 Project
		%h3 Join us in walking just 30 minutes a day, 
		%h3 for a healthier, happier you!
		= link_to "Click Here To Join Today!", signup_path, class: "btn btn-large btn-primary"
		%p
		%p Like us on Facebook and Share with your Friends!
		.fb-like{:data=>{:href => "https://www.walk-30.com", :send => "true", :width => "450", :show_faces => "false"}}
		
	-# %hr
	
	.row-fluid.marketing
		.span6
			%h4 Why?
			%p	
				We sit too much and it shows. Obesity in America is at an all-time high. 
				Diabetes is more and more common. Cardiovascular disease is still the 
				leading cause of death. That's the bad news. 
				The good news is that moderate exercise is 
				one of the most effective ways to prevent many of these chronic conditions. 
				We'd be significantly healthier if we each walked just 30 minutes a day.
		.span6
			
			%h4 What?
			%p 
				We want everyone to find time for a daily walk, but 
				know that exercise plans sometimes fall by the wayside.
				Each day, we'll send you a "Walk30!" text message, encouraging you to step 
				out for a short walk. 
				By responding to these messages, you can help us find the best times for your 
				daily reminder 
				and let us know that you're part of a community that's committed to better health.

			

app/views/static_pages/instructions.html.haml
-provide(:title, 'Instructions')
.container-narrow
	%h3 How it works
	%p	
		We'll send you a text message each day, which will remind you to go for a short walk.
		If the reminder comes at a good time, let us know by replying "yes". 
		If the reminder comes at a bad time, let us know by replying "no". We'll
		try to send reminders at convenient times. Let us know how we're doing!
	
	%p
	%p
	%h3 What if I don't want to participate anymore?
	%p 	
		Easy! Just reply "quit" to one of message, and we won't bother you anymore. You can
		also 
		=link_to "contact us", contact_path
		via email to let us know you're done. 
		
	%h3 What's the ultimate goal?
	%p
		Our goal is to help people to stay active. 
		We think that daily reminders might help people be more consistent with their
		exercise routines. We're using the Walk30 Project as a way to test this idea,
		and to help us discover the most effective and minimally intrusive
		ways to motivate people like you. 
		
	%h3 How do I sign up?
	=link_to "Click right here!", signup_path

app/views/static_pages/twilio_receive.xml.haml
- sms = @sms
%Response
	-if sms
		%SMS #{sms} 
		

app/views/static_pages/welcome.html.haml
-provide(:title, 'Welcome!')
.container-narrow
	.jumbotron.hero-unit
		%h2 Welcome To The Walk30 Project!
		%h3 Like us on Facebook and share with your friends!
		.fb-like{:data=>{:href => "https://www.walk-30.com", :send => "true", :width => "450", :show_faces => "false"}}

.container-narrow
	%h3 How it works
	%p	
		We'll send you a text message each day, which will remind you to go for a short walk.
		If the reminder comes at a good time, let us know by replying "yes". 
		If the reminder comes at a bad time, let us know by replying "no". We'll
		try to send reminders at convenient times. Let us know how we're doing!
	
	%p
	%p
	%h3 What if I don't want to participate anymore?
	%p 	
		Easy! Just reply "quit" to one of message, and we won't bother you anymore. You can
		also 
		=link_to "contact us", contact_path
		via email to let us know you're done. 
		
	%h3 What's the ultimate goal?
	%p
		Our goal is to help people to stay active. 
		We think that daily reminders might help people be more consistent with their
		exercise routines. We're using the Walk30 Project as a way to test this idea,
		and to help us discover the most effective and minimally intrusive
		ways to motivate people like you.