config/routes.rb
Walk30Experiment::Application.routes.draw do
  
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  devise_scope :user do
    match "/login", to: "devise/sessions#new"
  end
    
  resources :participants do
    collection do
      get :active
      put :setNextReminders
      get :mass_message
    end
    member do
      post :deliverMessage
    end
  end

  get "/twilio/receive/" => "static_pages#twilio_receive", :defaults => { :format => 'xml' } 

  resources :messages do
    collection do
      put :cancel_pending
      put :autoflag
    end
    member do
      put :deliver
      put :cancel
      put :flagPositive
      put :flagNegative
      put :flagNeutral
    end
  end

  root to: 'static_pages#home'
  match '/contact', to: 'static_pages#contact'
  match '/signup', to: "participants#new"
  match '/instructions', to: 'static_pages#instructions'
  match '/welcome', to: 'static_pages#welcome'
  

end

app/models/participant.rb
# == Schema Information
#
# Table name: participants
#
#  id                  :integer          not null, primary key
#  email               :string(255)
#  age                 :integer
#  zip_code            :string(255)
#  is_male             :boolean
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  phone               :string(255)
#  status              :integer
#  experiment_begun_at :datetime
#  experiment_ended_at :datetime
#

class Participant < ActiveRecord::Base
  attr_accessible :age, :email, :is_male, :phone, :zip_code, :status, :morning_reminder, :walked_last_week, :time_zone
  attr_accessible :reminder_strategy
  has_many :messages, :dependent => :destroy
  has_many :project_messages, :dependent => :destroy  

  default_scope order: 'participants.created_at DESC'
  
  ReceivedMessageHandlers = WalkReceivedAutoreply, ReceivedMessageAutoflag
  
  #Status values
  PENDING = 0
  ACTIVE = 1
  TERMINATED = 2
 
  #message status codes
  MESSAGE_PENDING = 0
     
  WELCOME_MESSAGE_CONTENT="Welcome to The Walk30 Project!\nWe'll send you a daily reminder to go for a walk. Reply \"quit\" to opt out..."
  DISCLAIMER_MESSAGE_CONTENT="Walk30: Message & data rates from your carrier may apply."
  
  before_save {|participant|
    participant.email=Participant.formatEmail(email)
    participant.phone=Participant.formatPhone(phone)
    participant.status ||= 0
  }
     
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  VALID_PHONE_REGEX = /^[\(\)0-9\- \+\.]{10,20}$/ 
  validates :phone, presence: true,
                    format: { with: VALID_PHONE_REGEX, message: "must be a valid phone number"}
  
  validates :zip_code, presence: true
  
  validates :time_zone, presence: true,
                        inclusion: {in: %w(PST EST CST MST AKST HAST NST), message: "Sorry, we currently support only North American Time Zones"}


  def time_zone_long
    case self.time_zone
    when "PST"
      "Pacific Time (US & Canada)"
    when "AKST"
      "Alaska"
    when "EST"
      "Eastern Time (US & Canada)" 
    when "CST"
      "Central Time (US & Canada)" 
    when "HST"
      "Hawaii"
    when "MST"
      "Mountain Time (US & Canada)"
    end
  end
    
#  def time_zone 
#    ActiveSupport::TimeZone.find_by_zipcode(self.zip_code)
#  end
                      
  
  def self.withPhone(phone)
    return Participant.find_by_phone(Participant.formatPhone(phone))
  end
    
  #Daily reminder stuff
  
      
  def reminderStrategyClass
    eval(self.reminder_strategy.camelize)
  end
  
  def setNextReminderMessage
    if not self.pendingReminderMessages?
      m = self.reminderStrategyClass.nextReminderMessage(self)
      m.save
    end
  end
  
  def pendingReminderMessages?
    self.reminderStrategyClass.pendingReminderMessages(self).length>0
  end
      
  def messagesUnflaggedOrChangedWithinNSeconds(n)
    return self.messages.select {|message| not message.flagged? or message.secondsSinceLastUpdate < n}    
  end
  
  #Setting and querying participant status
    
  def activate
    if true #self.pending?
      self.status = ACTIVE
      self.experiment_begun_at = DateTime.now()
      self.save
      #Send the welcome message
      begin
        if self.deliverMessage(WELCOME_MESSAGE_CONTENT,Message::TEXT)
          self.deliverMessage(DISCLAIMER_MESSAGE_CONTENT,Message::TEXT)
        else
          return false
        end
      rescue
        return false
      end
      return true
    end
  end
  
  def reactivate
    self.status = ACTIVE
    self.experiment_ended_at = nil
    self.save
  end
  
  def terminate
    self.status = TERMINATED
    self.experiment_ended_at = DateTime.now()
    self.save
  end
  
  def pending?
    self.status==PENDING
  end
  
  def active? 
    self.status==ACTIVE
  end

  def terminated? 
    self.status==TERMINATED
  end
  
  def days_active
    if self.experiment_begun_at
      if self.experiment_ended_at
        return (self.experiment_ended_at.to_f - self.experiment_begun_at.to_f)/86400.0
      else
        return (DateTime.now.to_f - self.experiment_begun_at.to_f)/86400.0
      end
    end
  end
    
  def days_terminated
    if self.experiment_ended_at
      return (DateTime.now.to_f - self.experiment_ended_at.to_f)/86400.0
    end
    return nil
  end

  def days_pending
    if self.experiment_begun_at
      return (self.days_pending - self.created_at.to_f)/86400.0
    elsif self.experiment_ended_at
      return (self.experiment_ended_at - self.created_at.to_f)/86400.0
    else
      return (DateTime.now.to_f - self.created_at.to_f)/86400.0
    end
  end
  
  def days_in_status
    if self.pending?
      return self.days_pending
    elsif self.active?
      return self.days_active
    elsif self.terminated?
      return self.days_terminated
    end
  end
  
  def statusString
    if self.active?
      return "ACTIVE"
    elsif self.terminated?
      return "TERMINATED"
      self.days_active.round.to_s
    elsif self.pending?
      return "PENDING"
    end
  end
  
  def daysInStatus
    if self.active?
      return self.days_active
    elsif self.terminated?
      return self.days_terminated
      self.days_active.round.to_s
    elsif self.pending?
      return self.days_pending
    end
  end
  
  #Message handling
  
  def deliverMessage(content,medium)
    message = self.messages.build(content:content,medium:medium,status:Message::PENDING)
    message.save
    message.deliver
  end
  
  def receiveMessage(content,medium)
    message = self.messages.build(content:content,medium:medium,status:Message::RECEIVED)
    message.save
    ReceivedMessageHandlers.each do |h| 
      h.respondToMessage(message)
    end
    return message
  end

  def messageDelivered(message)
    return message
  end

                     
  protected
  def self.formatPhone(phone)
    return phone.gsub(/\D/, '')
  end
  
  def self.formatEmail(email)
    return email.downcase
  end
    
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_filter :authenticate_user!, except: [:new, :create]
  
  def new
    @participant=Participant.new
  end
  
  def create
    @participant = Participant.new(params[:participant])
    #Randomly assign a reminder strategy
    @participant.reminder_strategy = [IntervalConsistentStrategy,IntervalSampleStrategy].sample.name.underscore
    #if verify_recaptcha
      #flash.discard(:recaptcha_error)
      if @participant.save
        if @participant.activate
          redirect_to welcome_path
        else
          Participant.delete(@participant.id)
          flash[:error] = "Try again:\n We can't send text messages to the phone number you provided."
          redirect_to signup_path
        end
      else
        render 'new'
      end
    #else
      #@participant.valid?
      #flash[:recaptcha_error] = "Try again:\n Your captcha response didn't match. Are you a robot?"
      #render 'new'
    #end
  end  
  
  def update
    puts params
    p = Participant.find(params[:id])
    if params[:activate]
      p.activate
    end
    if params[:reactivate]
      p.reactivate
    end
    if params[:terminate]
      p.terminate
    end
    p.save
    redirect_to request.referer
  end

  def deliverMessage
    if params[:delay_in_hours] == ''
      Participant.find(params[:id]).deliverMessage(params[:content],params[:medium])
    else
      time = DateTime.now() + params[:delay_in_hours].to_f/24
      Participant.find(params[:id]).pendingMessageWithTime(params[:content],params[:medium],time)
    end
    redirect_to request.referer
  end	
  
  def mass_message
    medium = Message::TEXT
    content = params[:content]
    status = params[:participant_status]
    timing = params[:timing]
    if status and timing and content and content.length > 0 and params[:submit] == "schedule_message"
      Participant.find_all_by_status(status).each do |p|
        Time.zone = "Pacific Time (US & Canada)"        
        case timing
        when "with_next_pending_message" 
          time = p.messages.find_all_by_status(Message::PENDING).map {|m| m.scheduled_at}.min
        when "next_noon_local"
          tString = (DateTime.tomorrow-24*60*60).to_s + " 12:00 " + p.time_zone_long
          time = DateTime.strptime(tString, '%Y-%m-%d %k:%M %Z')   
          while time < DateTime.now
            time += 24*60*60
          end
        when "tomorrow_noon_local"
          tString = DateTime.tomorrow.to_s + " 12:00 " + p.time_zone_long
          time = DateTime.strptime(tString, '%Y-%m-%d %k:%M %Z')              
        when "in_15_minutes"
          time = DateTime.now + 15.0/(24*60)
        end
        puts time
        if time
          message = p.messages.build(medium:medium,status:Message::PENDING,content:content, scheduled_at:time)
          message.save
        end
      end
      redirect_to active_participants_path
    end                            
  end

  def setNextReminders    
    Participant.find_all_by_status(Participant::ACTIVE).each {|p| p.setNextReminderMessage}
    redirect_to request.referer    
  end
          
  def active
    @participants = Participant.paginate  :page => params[:page], :per_page => 20, 
                                          :conditions => ['status = ?', Participant::ACTIVE]
    if params[:message_window_in_days]
      @message_window_in_days = params[:message_window_in_days].to_f
    else
      @message_window_in_days = 1.25
    end
  end
  
  def show
    @participant = Participant.find(params[:id])
    @message = @participant.messages.build
    @messages = @participant.messages(page: params[:page]).sort_by {|message| message.id}
  end
  
  def index
    @participants = Participant.paginate(page: params[:page])
  end  
    
  def destroy
    Participant.find(params[:id]).delete
    redirect_to request.referer
  end
    
end

app/helpers/participants_helper.rb
module ParticipantsHelper
    
end

app/views/participants/_action_paths.html.haml
-if participant.pending?
	=link_to "activate", participant_path(participant,activate:true), :method => :put, :activate=>true
	=link_to "delete", participant, :method => :delete
-elsif participant.active?
	=link_to "terminate", participant_path(participant,terminate:true), :method => :put
-elsif participant.terminated?
	=link_to "reactivate", participant_path(participant,reactivate:true), :method => :put
	=link_to "delete", participant, :method => :delete

app/views/participants/_active_participant_table.haml
-if defined? header and header==true
	%tr
		%th ID
		%th Date
		%th Time (local)
		%th Message Sent
		%th Message Received
		%th Actions
			
-if defined? participant and defined? messages
	%tr
		%td= link_to participant.id, participant
	-messages.each do |m|
		-if m.delivered? or m.received?
			-time = m.sent_at
		-elsif m.pending? 
			-time = m.scheduled_at
		-else
			-time = m.created_at
		-time = time.in_time_zone(m.participant.time_zone_long)
		%tr
			%td
			%td= time.strftime("%m/%d")
			%td= time.strftime("%I:%M%p")
			-if m.delivered? or m.pending? or m.canceled?
				%td= m.summaryString
				%td
			-elsif m.received?
				%td
				%td= m.summaryString
			%td{:nowrap=>true}
				=render "/messages/action_paths", :message=>m

app/views/participants/_table.html.haml
%table
	%tr
		%th ID
		%th STATUS
		%th Days in STATUS
		%th Reminder Strategy
		%th EMAIL
		%th PHONE
		%th ZIP
		%th Time Zone
		%th Messages Delivered
		%th Messages Received
		%th Messages Pending
		%th Actions
	-participants.each do |p|
		%tr
			%td= link_to p.id, p	
			%td= p.statusString
			%td= '%.2f' % p.days_in_status
			%th= p.reminder_strategy
			%td= p.email
			%td= p.phone
			%td= p.zip_code
			%td= p.time_zone
			%td= p.messages.where(status:Message::DELIVERED).length
			%td= p.messages.where(status:Message::RECEIVED).length
			%td= p.messages.where(status:Message::PENDING).length
			%td{:nowrap=>true}= render "/participants/action_paths", :participant=>p
				

app/views/participants/active.html.haml
-provide(:title, 'Active Participants')

%h2.offset3 
	All Pending Messages:
	=link_to "Cancel Only", cancel_pending_messages_path, :method => :put
	,
	=link_to "Cancel+Delete", cancel_pending_messages_path(:delete=>true), :method => :put
	%p
	All Daily Reminders:
	=link_to "Autoflag Received", autoflag_messages_path(:type=>"DailyReminderMessage"), :method => :put
	%p
	All Active Participants:
	=link_to "Schedule Next Reminder", setNextReminders_participants_path, :method => :put	
		
%h1 Active Participants Only

=will_paginate

%table{:cellspacing => "5"}
	=render "/participants/active_participant_table", :header=>true
	-@participants.each do |participant|
		-#messages = participant.messagesUnflaggedOrChangedWithinNSeconds(16*3600).sort_by{|message| message.id}
		-messages = participant.messages.select {|m| m.secondsSinceLastUpdate < @message_window_in_days*24*60*60}
		-messages.sort! {|a,b|  (b.sent_at ? b.sent_at : b.scheduled_at) <=> (a.sent_at ? a.sent_at : a.scheduled_at)}
		=render "/participants/active_participant_table", :participant=>participant, :messages=>messages
	

app/views/participants/index.html.haml
-provide(:title, 'All Participants')
%h1 All Participants

=will_paginate

=render "/participants/table", :participants=>@participants

app/views/participants/mass_message.html.haml
%h1 Mass Message Participants

%form.form-horizontal.offset2{action:mass_message_participants_path,method:"get"}
	.control-group
		.controls
			%textarea{name:"content",id:"content",placeholder:"message...",rows:2}
	.control-group
		%label.control-label{for:"timing"} Timing
		.controls
			%select{name:"timing",id:"timing"}
				%option{value:"with_next_pending_message"} With Next Pending Message
				%option{value:"next_noon_local"} At the next noon, local time
				%option{value:"tomorrow_noon_local"} Tomorrow at noon, local time
				%option{value:"in_15_minutes"} In 15 minutes
	.control-group
		%label.control-label{for:"participant_status"} Participant status
		.controls
			%select{name:"participant_status",id:"participant_status"}
				%option{value:Participant::ACTIVE} Active
				%option{value:Participant::PENDING} Pending
				%option{value:Participant::TERMINATED} Terminated
	.control-group
		.controls
			%button.btn{type:"submit",name:"submit",value:"schedule_message"} Submit

app/views/participants/new.html.erb
<h1>Participants#new</h1>
<p>Find me in app/views/participants/new.html.erb</p>

app/views/participants/new.html.haml
-provide(:title, 'Sign Up!')

.container-narrow
	%h1 Sign Up!
	.row
		.span4.offset2
			= form_for @participant do |f|
				= render 'shared/error_messages', object: f.object
				%h2 How should we be in touch?
				= f.label :email
				= f.text_field :email
				= f.label :phone, "Cellphone Number"
				= f.text_field :phone
				= f.label :morning_reminder, "When would you prefer your Walk30 reminder?"
				= f.radio_button :morning_reminder, true
				Morning
				%p
				= f.radio_button :morning_reminder, false
				Afternoon
				%p
				%h2 Where are you located?
				= f.label :time_zone, "Time Zone Abbreviation (Example: PST, EST)"
				= f.text_field :time_zone
				= f.label :zip_code, "Zip Code/Area Code"
				= f.text_field :zip_code
				%h2 Tell us about yourself...
				= f.label :age
				= f.number_field :age
				= f.label :is_male, "Gender"
				%p
				= f.radio_button :is_male, true
				Male
				%p
				= f.radio_button :is_male, false
				Female
				%p
				= f.label :walked_last_week, "How many times did you walk for at least 30 minutes in the last week?"
				= f.number_field :walked_last_week
				-#%h2 Prove you're not a robot...
				= #recaptcha_tags :ssl=>true
				%p			
				%p
				%h2 And finally...
				= f.submit "Sign Me Up!", class: "btn btn-large btn-primary"
				
				

app/views/participants/show.html.haml
-provide(:title, @participant.id)
.offset3
	%h2 
		=@participant.email 
		&nbsp; &nbsp;
		= render "/participants/action_paths", :participant=>@participant

= render "/participants/table", :participants=>[@participant]

		
%hr

-#render "/messages/console", :message=>@message

.offset1
	=form_tag deliverMessage_participant_path, :method => 'post' do
		Message
		%p
		=text_area_tag :content
		%p
		Medium:
		=select_tag :medium, options_for_select([["TEST Message",Message::TEST],["TEXT Message",Message::TEXT]]), :cols=>12
		%p
		Delay in hours:
		=number_field_tag :delay_in_hours, :cols=>12
		%p
		=submit_tag "Send Message"
	


%hr
=render "/messages/table", :messages=>@messages