config/routes.rb
Walk30Experiment::Application.routes.draw do
  
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  devise_scope :user do
    match "/login", to: "devise/sessions#new"
  end
    
  resources :participants do
    collection do
      get :active
      put :setNextReminders
      get :mass_message
    end
    member do
      post :deliverMessage
    end
  end

  get "/twilio/receive/" => "static_pages#twilio_receive", :defaults => { :format => 'xml' } 

  resources :messages do
    collection do
      put :cancel_pending
      put :autoflag
    end
    member do
      put :deliver
      put :cancel
      put :flagPositive
      put :flagNegative
      put :flagNeutral
    end
  end

  root to: 'static_pages#home'
  match '/contact', to: 'static_pages#contact'
  match '/signup', to: "participants#new"
  match '/instructions', to: 'static_pages#instructions'
  match '/welcome', to: 'static_pages#welcome'
  

end

app/views/layouts/_ga.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-37329052-1']);
  _gaq.push(['_setDomainName', 'walk-30.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/_header.html.erb
<div class="masthead">	
		<ul class="nav nav-pills pull-right">
			<li><%= link_to "Home", root_path %></li>
        	<li><%= link_to "Contact", contact_path %></li>
        	<li><%= link_to "Instructions", instructions_path %></li>
        	<% if user_signed_in? %>
        		<li><%= link_to "Active Participants", active_participants_path %></li>
        		<li><%= link_to "All Participants", participants_path %></li>
        		<li><%= link_to "Mass Message", mass_message_participants_path %></li>
        		<li><%= link_to "Settings", edit_user_registration_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                </li>
        	<% end %>
        		
		</ul>
	<h3 class="muted">Walk30</h3>	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Walk30 Project | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]--> 
    <meta property="og:title" content="The Walk30 Project" />
	<meta property="og:type" content="website" />
	<meta property="og:url" content="https://www.walk-30.com" />
	<meta property="og:image" content="walk-30.png" />
	<meta property="og:site_name" content="The Walk30 Project" />
	<meta property="fb:app_id" content="10150429722210603" /> 
</head>
<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div>
	<div class="container-narrow">
	<%= render 'layouts/header' %>	
	
      	<%= render 'shared/flashes' %>
	
	</div>	
  	<%= yield %>
</div>
<% if Rails.env.production? %>
	<%= render 'layouts/ga' %>
<%end%>

</body>
</html>